#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys
from importlib.metadata import version

from git import Repo
from sphinx_pyproject import SphinxConfig

astrodb_utils_version = version("astrodb_utils")

config = SphinxConfig(
    "../pyproject.toml",
    globalns=globals(),
    config_overrides={"version": astrodb_utils_version, "release": astrodb_utils_version},
)

sys.path.insert(0, os.path.abspath("../.."))
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../schema"))

# Get markdown files for the template schema from astrodb-template-db/ repository

template_schema_path = os.path.join("pages", "getting_started", "template_schema", "astrodb-template-db")
if os.path.exists(template_schema_path):
    template_repo = Repo(template_schema_path)
    try:
        template_repo.git.reset("--hard")
        template_repo.remotes.origin.pull()
    except Exception as e:
        print(f"Error updating template schema repository: {e}")
        print(f"Using existing local copy of the template schema: {template_schema_path}")
else:
    url = "https://github.com/astrodbtoolkit/astrodb-template-db.git"
    try:
        Repo.clone_from(url, template_schema_path, branch="main")
    except Exception as e:
        print(f"Error cloning template schema repository: {e}")
        print(f"Please ensure the repository exists and is accessible: {url}")


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.


extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.coverage",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
    "nbsphinx",
    "pydata_sphinx_theme",
    'sphinx_mdinclude',
]


nbsphinx_prolog = """
This notebook is available at
https://github.com/astrodbtoolkit/astrodb_utils/tree/main/docs/{{ env.doc2path(env.docname, base=None) }}
"""
# Add any paths that contain templates here, relative to this directory.
# templates_path = ["_templates"]

napoleon_google_docstring = False
napoleon_use_param = False
napoleon_use_ivar = True

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "astrodb_utils"
copyright = "2024, Kelle Cruz, Arjun B. Savel, David Rodriguez"
author = "Kelle Cruz, Arjun B. Savel, David Rodriguez"
description = "Scripts for interacting with the AstroDB Toolkit"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# version = "0.1"
# The full version, including alpha/beta/rc tags.
# release = "0.1"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_
# _path and html_extra_path
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "../tests",
    "pages/template_schema/astrodb-template-db/*",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = "sphinx_book_theme"
html_theme = "pydata_sphinx_theme"
html_favicon = "_static/Toolkit-logo.png"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {
    "show_nav_level": 2,
    "logo": {
        "text": "AstroDB Toolkit",
        "image_light": "_static/Toolkit-logo.png",
        "image_dark": "_static/Toolkit-logo.png",
    }
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_logo = '_static/Toolkit-logo.png'


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "astrodb_utilsdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "astrodb_utils.tex",
        "astrodb_utils Documentation",
        "Kelle Cruz, Arjun B. Savel, David Rodriguez",
        "manual",
    )
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "astrodb_utils", "astrodb_utils Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "astrodb_utils",
        "astrodb_utils Documentation",
        author,
        "astrodb_utils",
        description,
        "Miscellaneous",
    )
]
